[package]
name = "lib_lemm"
repository = "https://github.com/juicermv/le-mod-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
ascii = "1.1.0"
flate2 = "1.1.1"
strum = { version = "0.27.1" }
strum_macros = "0.27.1"
