[workspace]
resolver = "2"
members = ["crates/lemm_app", "crates/lib_lemm"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
