[application]
name = "LE Mod Manager"
out_dir = "dist"

[web.app]

title = "LE Mod Manager"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "io.github.juicermv"
publisher = "juicermv"
version = "0.1.0"
short_description = "A mod manager for Dark Souls Lighting Engine."

# HTML title tag content
[bundle.windows]
tsp = true
allow_downgrades = false

[bundle.windows.webview_install_mode.OfflineInstaller]
silent = true
