[package]
name = "lib_lemm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
ascii = "1.1.0"
flate2 = "1.1.1"
text_io = "0.1.13"
strum = { version = "0.27.1" }
strum_macros = "0.27.1"
