name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Cargo Binary Install
        run: Set-ExecutionPolicy Unrestricted -Scope Process; iex (iwr "https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.ps1").Content

      - name: Install Dioxus Client
        run: cargo binstall dioxus-cli

      - name: Build Bundle
        run: dx bundle --package lemm_app